name: Build Pure Unix Binary
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04 # Чистый Linux-раннер
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pygame nuitka setuptools

      - name: Compile to Unix Binary
        run: |
          # Nuitka превращает .py в один исполняемый файл 'program'
          # Мы убираем все расширения, чтобы был просто Unix-стиль
          python -m nuitka --onefile --standalone --plugin-enable=pygame --output-filename=program main.py

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: unix-program
          path: program
