name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Обновил до v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновил до v5
        with:
          python-version: '3.11' # 3.11 стабильнее всего для p4a сейчас

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake gettext libffi-dev libssl-dev build-essential
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 setuptools

       - name: Create buildozer.spec
        run: |
          buildozer init
          # Тут мы заменяем стандартные строки на нужные нам через sed
          sed -i 's/requirements = python3,kivy/requirements = python3,pygame==2.5.2,setuptools/' buildozer.spec
          sed -i 's/orientation = portrait/orientation = landscape/' buildozer.spec
          # Если твой main.py в подпапке src, раскомментируй строку ниже:
          # sed -i 's|source.dir = .|source.dir = ./src|' buildozer.spec


      - name: Build APK
        run: |
          # Если main.py в подпапке, убедись, что в buildozer.spec указан source.dir
          yes y | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # ВОТ ОНО ИСПРАВЛЕНИЕ v4
        with:
          name: flappy-bar-apk
          path: bin/*.apk
          compression-level: 0 # Для APK лучше не сжимать повторно
